### PR TITLE
Handle resources with no methods and empty response bodies

### PR DESCRIPTION
**Pull request by samskiter**
I had some errors while parsing some valid (and hopefully not too unusual) RAML. Hope this is OK?

### CODE REVIEW

**Comment by samskiter** [comment]
Fixed the merge conflicts

**Comment by samskiter** [comment]
Has anyone had a chance to look at this yet? @domix ?

**Comment by domix** [comment]
Sorry @samskiter I'll  review it shortly, then @atomsfat will released it.

Thanks for your contribution!

**Comment by samskiter** [comment]
Quick question, do I need to compile the coffeescript and commit it or is that done automatically?

**Comment by samskiter** [comment]
friendly ping, if you have the chance to look over, don't want to start forking too much...

**Comment by samskiter** [comment]
@domix I have a couple of PR's open now... are these projects still under active dev?

Here's another PR: https://github.com/gextech/raml2code-retrofit/pull/3

**Pull request merged**
